[package]
name = "hyphenation"
version = "0.5.0"

authors = ["ndr <ndr@qef.io>"]
license = "Apache-2.0/MIT"
repository = "https://github.com/ndr-qef/hyphenation"
homepage = "https://github.com/ndr-qef/hyphenation"
documentation = "https://ndr-qef.github.io/hyphenation"

readme = "README.md"
description = "Standard Knuth-Liang hyphenation based on the TeX UTF-8 patterns."
keywords = ["text", "typesetting"]


include = [ "Cargo.toml", "build.rs", "src/*", "tests/*", "benches/*"
          , "patterns/*", "README.md", "LICENSE-APACHE", "LICENSE-MIT" ]

build = "build.rs"


[dependencies]
fnv = "^1.0"
serde_json = "^0.8"
unicode-segmentation = "^0.1"

[build-dependencies]
pocket-resources = "^0.3"

[dev-dependencies]
lazy_static = "^0.2"
quickcheck = "^0.3"
