[package]
name = "hyphenation"
version = "0.1.1"

authors = ["ndr <ndr@qef.io>"]
license = "Apache-2.0/MIT"
readme = "README.md"
description = "Standard Knuth-Liang hyphenation based on the TeX UTF-8 patterns."
keywords = ["text", "typesetting"]

homepage = "https://github.com/ndr-qef/hyphenation"
repository = "https://github.com/ndr-qef/hyphenation"

include = ["src/*", "tests/*", "patterns/*", "Cargo.toml", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]


[dependencies]
lazy_static = "~0.1.15"
unicode-normalization = "~0.1.2"

[dev-dependencies]
quickcheck = "~0.2.25"
