[package]
name = "hyphenation"
version = "0.3.0"

authors = ["ndr <ndr@qef.io>"]
license = "Apache-2.0/MIT"
readme = "README.md"
description = "Standard Knuth-Liang hyphenation based on the TeX UTF-8 patterns."
keywords = ["text", "typesetting"]

homepage = "https://github.com/ndr-qef/hyphenation"
repository = "https://github.com/ndr-qef/hyphenation"

include = ["src/*", "tests/*", "patterns/*", "Cargo.toml", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]


[dependencies]
fnv = "^1.0"
lazy_static = "^0.1"
serde_json = "^0.7"
unicode-normalization = "^0.1"
unicode-segmentation = "^0.1"

[dev-dependencies]
quickcheck = "^0.2"
