[package]
name = "hyphenation_commons"
version = "0.6.0"  # version-locked to main `hyphenation` crate

authors = ["ndr <ndr@qef.io>"]
license = "Apache-2.0/MIT"
repository = "https://github.com/ndr-qef/hyphenation"
homepage = "https://github.com/ndr-qef/hyphenation"
documentation = "https://docs.rs/hyphenation"

description = "Proemial code shared by the hyphenation build script and library"

build = "build.rs"

[features]
default = ["serde_codegen"]
unstable = ["serde_derive"]

[dependencies]
fnv = "^1.0"
serde = "0.8"
serde_derive = { version = "0.8", optional = true }

[build-dependencies]
serde_codegen = { version = "0.8", optional = true }
